-- ================================================================
-- CAMPUS-EASE COMPLETE DATABASE SCHEMA
-- One Complete Schema File for All Tables
-- Created: December 19, 2025
-- ================================================================
-- Description: This file contains the complete database schema
-- for the Campus-Ease system including all user management,
-- attendance tracking, class management, face recognition,
-- community features, and reporting functionality.
-- ================================================================

-- ================================================================
-- SECTION 0: TRANSACTION START & CLEANUP
-- ================================================================
-- This section ensures a clean slate for schema recreation
-- ================================================================

BEGIN;

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Ensure schemas exist
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS public;

-- Set search path
SET search_path TO public, auth;

-- Drop dependent views first (to avoid dependency errors)
DROP VIEW IF EXISTS public.attendance_with_face_recognition CASCADE;
DROP VIEW IF EXISTS public.student_face_training_status CASCADE;

-- Drop all tables in reverse dependency order
DROP TABLE IF EXISTS public.recognition_logs CASCADE;
DROP TABLE IF EXISTS public.face_recognition_attendance CASCADE;
DROP TABLE IF EXISTS public.training_images CASCADE;
DROP TABLE IF EXISTS public.persons CASCADE;
DROP TABLE IF EXISTS public.face_recognition_config CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.report CASCADE;
DROP TABLE IF EXISTS public.community_messages CASCADE;
DROP TABLE IF EXISTS public.student_records CASCADE;
DROP TABLE IF EXISTS public.class_details CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.faculty CASCADE;
DROP TABLE IF EXISTS public.admin CASCADE;

-- Drop the trigger function if it exists
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- ================================================================
-- SECTION 1: USER MANAGEMENT TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 1.1 USERS TABLE (Students)
-- ----------------------------------------------------------------
-- Note: This table is being phased out in favor of student_records
-- but is maintained for backwards compatibility
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  user_id text UNIQUE NOT NULL,
  fname text NOT NULL,
  lname text NOT NULL,
  email text UNIQUE NOT NULL,
  mobile_num text,
  dob date,
  address text,
  emergency_contact text,
  course_taken text,
  profile_photo text,
  has_photo boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  role text DEFAULT 'student',
  auth_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  class_id text,
  verification_expiry timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_users_user_id ON public.users USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users USING btree (auth_id);
CREATE INDEX IF NOT EXISTS idx_users_class_id ON public.users USING btree (class_id);

-- ----------------------------------------------------------------
-- 1.2 STUDENT RECORDS TABLE (Primary Student Data)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text UNIQUE NOT NULL,
  auth_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  fname text NOT NULL,
  lname text NOT NULL,
  email text UNIQUE NOT NULL,
  mobile_num text,
  roll_no text UNIQUE NOT NULL,
  student_id text NOT NULL,
  dob date,
  address text,
  emergency_contact text,
  course_taken text,
  class_id text,
  department text,
  institute text DEFAULT 'CHARUSAT',
  semester integer DEFAULT 1,
  academic_year text,
  profile_photo text,
  role text DEFAULT 'student',
  email_verified boolean DEFAULT true,
  account_activated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT unique_student_user_id UNIQUE (user_id),
  CONSTRAINT unique_student_email UNIQUE (email),
  CONSTRAINT unique_student_roll_no UNIQUE (roll_no)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_student_records_user_id ON public.student_records USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_student_records_auth_id ON public.student_records USING btree (auth_id);
CREATE INDEX IF NOT EXISTS idx_student_records_class_id ON public.student_records USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_student_records_department ON public.student_records USING btree (department);
CREATE INDEX IF NOT EXISTS idx_student_records_roll_no ON public.student_records USING btree (roll_no);
CREATE INDEX IF NOT EXISTS idx_student_records_email ON public.student_records USING btree (email);
CREATE INDEX IF NOT EXISTS idx_student_records_student_id ON public.student_records USING btree (student_id);

COMMENT ON TABLE public.student_records IS 'Primary table for student records with enhanced class management support';
COMMENT ON COLUMN public.student_records.user_id IS 'Unique student identifier (e.g., 23DIT001)';
COMMENT ON COLUMN public.student_records.auth_id IS 'Links to Supabase auth.users when account is activated';
COMMENT ON COLUMN public.student_records.account_activated IS 'FALSE if using default password, TRUE after password change';

-- ----------------------------------------------------------------
-- 1.3 FACULTY TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.faculty (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  user_id text UNIQUE NOT NULL,
  fname text NOT NULL,
  lname text NOT NULL,
  email text UNIQUE NOT NULL,
  mobile_num text,
  dob date,
  address text,
  emergency_contact text,
  course_taken text,
  profile_photo text,
  has_photo boolean DEFAULT false,
  email_verified boolean DEFAULT true,
  role text DEFAULT 'faculty',
  verification_expiry timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_faculty_user_id ON public.faculty USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_faculty_email ON public.faculty USING btree (email);

COMMENT ON TABLE public.faculty IS 'Faculty member records with authentication integration';

-- ----------------------------------------------------------------
-- 1.4 ADMIN TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  user_id text UNIQUE NOT NULL,
  fname text NOT NULL,
  lname text NOT NULL,
  email text UNIQUE NOT NULL,
  mobile_num text,
  dob date,
  address text,
  emergency_contact text,
  course_taken text,
  profile_photo text,
  has_photo boolean DEFAULT false,
  email_verified boolean DEFAULT true,
  role text DEFAULT 'admin',
  verification_expiry timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_admin_user_id ON public.admin USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_admin_email ON public.admin USING btree (email);

COMMENT ON TABLE public.admin IS 'System administrator records with full access';

-- ================================================================
-- SECTION 2: CLASS MANAGEMENT TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 2.1 CLASS DETAILS TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.class_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name text NOT NULL,
  class_id text UNIQUE NOT NULL,
  department text NOT NULL,
  institute text NOT NULL,
  semester integer NOT NULL DEFAULT 1,
  academic_year text NOT NULL,
  description text,
  course_taken text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT unique_class_id UNIQUE (class_id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_class_details_class_id ON public.class_details USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_class_details_department ON public.class_details USING btree (department);
CREATE INDEX IF NOT EXISTS idx_class_details_institute ON public.class_details USING btree (institute);
CREATE INDEX IF NOT EXISTS idx_class_details_academic_year ON public.class_details USING btree (academic_year);

COMMENT ON TABLE public.class_details IS 'Class/course information for student grouping and management';

-- ================================================================
-- SECTION 3: ATTENDANCE SYSTEM TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 3.1 ATTENDANCE TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  student_id text NOT NULL,
  student_name text NOT NULL,
  roll_no text,
  class_id text,
  department text,
  date date NOT NULL,
  subject text NOT NULL,
  class_type text NOT NULL,
  status text NOT NULL CHECK (status IN ('present', 'absent', 'late')),
  marked_by text NOT NULL,
  faculty_name text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT unique_attendance_record UNIQUE (user_id, date, subject, class_id, marked_by)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_attendance_user_id ON public.attendance USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student_id ON public.attendance USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_class_id ON public.attendance USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance USING btree (date DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_subject ON public.attendance USING btree (subject);
CREATE INDEX IF NOT EXISTS idx_attendance_marked_by ON public.attendance USING btree (marked_by);
CREATE INDEX IF NOT EXISTS idx_attendance_faculty_name ON public.attendance USING btree (faculty_name);

COMMENT ON TABLE public.attendance IS 'Enhanced attendance tracking with class-based faculty management';
COMMENT ON COLUMN public.attendance.user_id IS 'References student_records.user_id';
COMMENT ON COLUMN public.attendance.class_id IS 'References class_details.class_id';
COMMENT ON COLUMN public.attendance.faculty_name IS 'Name of faculty member who marked attendance';

-- ================================================================
-- SECTION 4: FACE RECOGNITION TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 4.1 PERSONS TABLE (Face Recognition)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.persons (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name varchar(255) NOT NULL,
  student_id varchar(50) UNIQUE,
  employee_id varchar(50) UNIQUE,
  email varchar(255),
  department varchar(100),
  role varchar(50) DEFAULT 'student',
  face_embedding text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chk_person_id CHECK (student_id IS NOT NULL OR employee_id IS NOT NULL),
  CONSTRAINT chk_role CHECK (role IN ('student', 'faculty', 'staff', 'admin'))
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_persons_student_id ON public.persons USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_persons_employee_id ON public.persons USING btree (employee_id);
CREATE INDEX IF NOT EXISTS idx_persons_role ON public.persons USING btree (role);
CREATE INDEX IF NOT EXISTS idx_persons_active ON public.persons USING btree (is_active);

COMMENT ON TABLE public.persons IS 'Stores person data with face embeddings for recognition';
COMMENT ON COLUMN public.persons.face_embedding IS 'Base64 encoded face embedding vector';

-- ----------------------------------------------------------------
-- 4.2 TRAINING IMAGES TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.training_images (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  person_id uuid REFERENCES public.persons(id) ON DELETE CASCADE,
  image_path varchar(500),
  image_data bytea,
  image_url varchar(500),
  image_hash varchar(64),
  face_confidence float DEFAULT 0.0,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chk_image_source CHECK (image_path IS NOT NULL OR image_data IS NOT NULL OR image_url IS NOT NULL)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_training_images_person_id ON public.training_images USING btree (person_id);
CREATE INDEX IF NOT EXISTS idx_training_images_primary ON public.training_images USING btree (is_primary);

COMMENT ON TABLE public.training_images IS 'Training images used for face recognition model';
COMMENT ON COLUMN public.training_images.image_hash IS 'SHA256 hash for duplicate detection';

-- ----------------------------------------------------------------
-- 4.3 FACE RECOGNITION ATTENDANCE TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.face_recognition_attendance (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  attendance_id uuid,
  person_id uuid REFERENCES public.persons(id) ON DELETE CASCADE,
  student_id varchar(50),
  class_id varchar(100) NOT NULL,
  date date NOT NULL,
  subject varchar(100),
  class_type varchar(50),
  status varchar(20) DEFAULT 'present',
  confidence_score float DEFAULT 0.0,
  recognition_method varchar(50) DEFAULT 'face_recognition',
  marked_by varchar(50),
  faculty_name varchar(255),
  class_photo_url varchar(500),
  bbox_coordinates jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chk_status CHECK (status IN ('present', 'absent', 'late')),
  CONSTRAINT chk_recognition_method CHECK (recognition_method IN ('face_recognition', 'manual', 'hybrid')),
  UNIQUE(student_id, date, subject, marked_by)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_fr_attendance_student_id ON public.face_recognition_attendance USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_fr_attendance_class_date ON public.face_recognition_attendance USING btree (class_id, date);
CREATE INDEX IF NOT EXISTS idx_fr_attendance_marked_by ON public.face_recognition_attendance USING btree (marked_by);
CREATE INDEX IF NOT EXISTS idx_fr_attendance_date ON public.face_recognition_attendance USING btree (date);

COMMENT ON TABLE public.face_recognition_attendance IS 'Attendance records from face recognition with confidence scores';
COMMENT ON COLUMN public.face_recognition_attendance.bbox_coordinates IS 'Bounding box of detected face in JSON format';

-- ----------------------------------------------------------------
-- 4.4 RECOGNITION LOGS TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.recognition_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id uuid DEFAULT gen_random_uuid(),
  image_path varchar(500),
  total_faces_detected integer DEFAULT 0,
  recognized_faces integer DEFAULT 0,
  unrecognized_faces integer DEFAULT 0,
  processing_time_ms integer,
  confidence_threshold float,
  class_id varchar(100),
  marked_by varchar(50),
  recognition_results jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now()
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_recognition_logs_session ON public.recognition_logs USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_recognition_logs_class ON public.recognition_logs USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_recognition_logs_date ON public.recognition_logs USING btree (created_at);

COMMENT ON TABLE public.recognition_logs IS 'Logs of face recognition processing sessions';

-- ----------------------------------------------------------------
-- 4.5 FACE RECOGNITION CONFIG TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.face_recognition_config (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  config_key varchar(100) UNIQUE NOT NULL,
  config_value text,
  description text,
  updated_by varchar(50),
  updated_at timestamp with time zone DEFAULT now()
) TABLESPACE pg_default;

COMMENT ON TABLE public.face_recognition_config IS 'System configuration for face recognition parameters';

-- Insert default configuration values
INSERT INTO public.face_recognition_config (config_key, config_value, description) VALUES
  ('similarity_threshold', '0.4', 'Minimum similarity score for face recognition (0.0-1.0)'),
  ('max_training_images', '10', 'Maximum number of training images per person'),
  ('cache_duration_minutes', '5', 'Duration to cache face embeddings in memory'),
  ('recognition_timeout_seconds', '30', 'Maximum time for face recognition processing'),
  ('max_faces_per_image', '100', 'Maximum number of faces to detect in a single image')
ON CONFLICT (config_key) DO NOTHING;

-- ================================================================
-- SECTION 5: COMMUNITY & COMMUNICATION TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 5.1 COMMUNITY MESSAGES TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.community_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid NOT NULL REFERENCES auth.users(id),
  sender_name text NOT NULL,
  sender_role text NOT NULL,
  content text NOT NULL,
  college_id text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES auth.users(id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_community_messages_created_at ON public.community_messages USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_community_messages_sender ON public.community_messages USING btree (sender_id);

COMMENT ON TABLE public.community_messages IS 'Community chat messages for student-faculty communication';

-- ================================================================
-- SECTION 6: REPORTING & PROBLEM TRACKING TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 6.1 REPORT TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.report (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Problem_Category" text,
  "Reporter_Type" text,
  "Location" text,
  "class_No" bigint,
  "Impact_Scope" text,
  "Occurrence_Pattern" text,
  images text,
  priority_level integer DEFAULT 1,
  priority_text text DEFAULT 'Medium',
  description jsonb,
  resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  reporter_id uuid REFERENCES auth.users(id),
  CONSTRAINT fk_reporter FOREIGN KEY (reporter_id) REFERENCES auth.users(id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_report_priority ON public.report USING btree (priority_level DESC);
CREATE INDEX IF NOT EXISTS idx_report_reporter ON public.report USING btree (reporter_id);

COMMENT ON TABLE public.report IS 'Problem reporting and tracking system for campus issues';

-- ================================================================
-- SECTION 7: FOREIGN KEY CONSTRAINTS
-- ================================================================

-- Add foreign key from student_records to class_details
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_student_class'
    AND table_name = 'student_records'
  ) THEN
    ALTER TABLE public.student_records 
    ADD CONSTRAINT fk_student_class 
    FOREIGN KEY (class_id) 
    REFERENCES public.class_details(class_id) 
    ON DELETE SET NULL;
  END IF;
END
$$;

-- Add foreign key from attendance to student_records
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_attendance_student'
    AND table_name = 'attendance'
  ) THEN
    ALTER TABLE public.attendance 
    ADD CONSTRAINT fk_attendance_student 
    FOREIGN KEY (user_id) 
    REFERENCES public.student_records(user_id) 
    ON DELETE CASCADE;
  END IF;
END
$$;

-- Add foreign key from attendance to class_details
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_attendance_class'
    AND table_name = 'attendance'
  ) THEN
    ALTER TABLE public.attendance 
    ADD CONSTRAINT fk_attendance_class 
    FOREIGN KEY (class_id) 
    REFERENCES public.class_details(class_id) 
    ON DELETE SET NULL;
  END IF;
END
$$;

-- ================================================================
-- SECTION 8: TRIGGERS FOR AUTO-UPDATING TIMESTAMPS
-- ================================================================

-- Create or replace trigger function for updating timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- Apply triggers to tables with updated_at columns
DROP TRIGGER IF EXISTS update_persons_updated_at ON public.persons;
CREATE TRIGGER update_persons_updated_at 
    BEFORE UPDATE ON public.persons 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_fr_attendance_updated_at ON public.face_recognition_attendance;
CREATE TRIGGER update_fr_attendance_updated_at 
    BEFORE UPDATE ON public.face_recognition_attendance 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_student_records_updated_at ON public.student_records;
CREATE TRIGGER update_student_records_updated_at 
    BEFORE UPDATE ON public.student_records 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_class_details_updated_at ON public.class_details;
CREATE TRIGGER update_class_details_updated_at 
    BEFORE UPDATE ON public.class_details 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_attendance_updated_at ON public.attendance;
CREATE TRIGGER update_attendance_updated_at 
    BEFORE UPDATE ON public.attendance 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ================================================================
-- SECTION 9: VIEWS FOR COMPLEX QUERIES
-- ================================================================

-- ----------------------------------------------------------------
-- 9.1 STUDENT FACE TRAINING STATUS VIEW
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW student_face_training_status AS
SELECT 
    sr.user_id as student_id,
    sr.fname,
    sr.lname,
    sr.department,
    sr.class_id,
    p.id as person_id,
    p.face_embedding IS NOT NULL as has_face_training,
    p.created_at as training_date,
    (SELECT COUNT(*) FROM training_images ti WHERE ti.person_id = p.id) as training_images_count,
    p.is_active as face_recognition_active
FROM student_records sr
LEFT JOIN persons p ON sr.user_id = p.student_id;

COMMENT ON VIEW student_face_training_status IS 'Shows face recognition training status for each student';

-- ----------------------------------------------------------------
-- 9.2 ATTENDANCE WITH FACE RECOGNITION DETAILS VIEW
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW attendance_with_face_recognition AS
SELECT 
    a.*,
    fra.confidence_score,
    fra.recognition_method,
    fra.bbox_coordinates,
    fra.class_photo_url,
    p.name as person_name,
    p.face_embedding IS NOT NULL as has_face_training
FROM attendance a
LEFT JOIN face_recognition_attendance fra ON 
    fra.student_id = a.user_id AND 
    fra.date = a.date AND 
    fra.subject = a.subject AND
    fra.marked_by = a.marked_by
LEFT JOIN persons p ON p.student_id = a.user_id;

COMMENT ON VIEW attendance_with_face_recognition IS 'Combines regular attendance with face recognition data';

-- ================================================================
-- SECTION 10: SAMPLE DATA FOR TESTING
-- ================================================================

-- Insert sample class details
INSERT INTO public.class_details (class_name, class_id, department, institute, semester, academic_year, course_taken)
VALUES 
  ('DIT Sem 7', '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  ('IT Sem 5', '24IT1659', 'IT', 'CSPIT', 5, '2024-25', 'B.Tech IT - CSPIT'),
  ('CE Sem 3', '24CE1660', 'CE', 'CSPIT', 3, '2024-25', 'B.Tech CE - CSPIT'),
  ('CS Sem 6', '24CS1661', 'CS', 'DEPSTAR', 6, '2024-25', 'B.Tech CS - DEPSTAR')
ON CONFLICT (class_id) DO NOTHING;

-- Insert sample students
INSERT INTO public.student_records (
  user_id, fname, lname, email, roll_no, student_id, class_id, department, 
  institute, semester, academic_year, course_taken
)
VALUES 
  ('24DIT001', 'Yash', 'Ahir', '24dit001@charusat.edu.in', '24DIT001', '24DIT001', 
   '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  ('24DIT002', 'Harsh', 'Shah', '24dit002@charusat.edu.in', '24DIT002', '24DIT002', 
   '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  ('24DIT003', 'Priya', 'Patel', '24dit003@charusat.edu.in', '24DIT003', '24DIT003', 
   '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR')
ON CONFLICT (user_id) DO NOTHING;

-- ================================================================
-- SECTION 11: VERIFICATION QUERIES
-- ================================================================

-- Check all table row counts
SELECT 'class_details' as table_name, count(*) as row_count FROM public.class_details
UNION ALL
SELECT 'student_records', count(*) FROM public.student_records
UNION ALL
SELECT 'users', count(*) FROM public.users
UNION ALL
SELECT 'faculty', count(*) FROM public.faculty
UNION ALL
SELECT 'admin', count(*) FROM public.admin
UNION ALL
SELECT 'attendance', count(*) FROM public.attendance
UNION ALL
SELECT 'persons', count(*) FROM public.persons
UNION ALL
SELECT 'training_images', count(*) FROM public.training_images
UNION ALL
SELECT 'face_recognition_attendance', count(*) FROM public.face_recognition_attendance
UNION ALL
SELECT 'community_messages', count(*) FROM public.community_messages
UNION ALL
SELECT 'report', count(*) FROM public.report;

-- Show class and student distribution
SELECT 
  cd.class_name,
  cd.department,
  cd.institute,
  cd.semester,
  COUNT(sr.user_id) as student_count
FROM public.class_details cd
LEFT JOIN public.student_records sr ON cd.class_id = sr.class_id
GROUP BY cd.class_name, cd.department, cd.institute, cd.semester
ORDER BY cd.department, cd.semester;

-- ================================================================
-- SECTION 12: ADDITIONAL TABLES FOR APP FEATURES
-- ================================================================

-- ----------------------------------------------------------------
-- 12.1 ANNOUNCEMENTS TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'high')),
  category text DEFAULT 'General',
  department text DEFAULT 'All',
  created_by uuid REFERENCES auth.users(id),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_announcements_active ON public.announcements USING btree (is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_announcements_priority ON public.announcements USING btree (priority);

COMMENT ON TABLE public.announcements IS 'Campus-wide announcements for students and faculty';

-- ----------------------------------------------------------------
-- 12.2 EVENT TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Ename" text NOT NULL,
  "Etype" text NOT NULL DEFAULT 'Academic',
  "Date" date NOT NULL,
  "Time" text NOT NULL,
  "Location" text NOT NULL,
  "Ephoto" text,
  "Description" text,
  capacity integer DEFAULT 100,
  registered_count integer DEFAULT 0,
  status text DEFAULT 'upcoming',
  department text,
  created_by text,
  contact_email text,
  contact_phone text,
  speaker text,
  registration_deadline timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_event_date ON public.event USING btree ("Date" ASC);
CREATE INDEX IF NOT EXISTS idx_event_type ON public.event USING btree ("Etype");

COMMENT ON TABLE public.event IS 'Campus events and activities';

-- ----------------------------------------------------------------
-- 12.3 EVENT REGISTRATIONS TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.event_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint REFERENCES public.event(id) ON DELETE CASCADE,
  user_id text NOT NULL,
  user_name text NOT NULL,
  user_email text NOT NULL,
  user_role text DEFAULT 'student',
  department text,
  semester integer,
  phone_number text,
  registration_date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  attendance_status text DEFAULT 'registered',
  notes text,
  UNIQUE(event_id, user_id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_event_registrations_event ON public.event_registrations USING btree (event_id);
CREATE INDEX IF NOT EXISTS idx_event_registrations_user ON public.event_registrations USING btree (user_id);

COMMENT ON TABLE public.event_registrations IS 'Event registration records';

-- ----------------------------------------------------------------
-- 12.4 RESOURCES TABLE (Study Materials)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.resources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  subject text NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_type text,
  file_size bigint,
  uploaded_by text NOT NULL,
  uploader_name text,
  uploader_role text DEFAULT 'student',
  department text,
  semester integer,
  is_approved boolean DEFAULT false,
  approved_by text,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_resources_approved ON public.resources USING btree (is_approved, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_resources_subject ON public.resources USING btree (subject);
CREATE INDEX IF NOT EXISTS idx_resources_uploader ON public.resources USING btree (uploaded_by);

COMMENT ON TABLE public.resources IS 'Study materials and resources shared by students and faculty';

-- ----------------------------------------------------------------
-- 12.5 CLASS TIMETABLES TABLE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.class_timetables (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id text NOT NULL,
  day_index integer NOT NULL CHECK (day_index >= 0 AND day_index <= 5),
  slot_index integer NOT NULL CHECK (slot_index >= 0 AND slot_index <= 5),
  course text NOT NULL,
  professor text,
  room text,
  is_lab boolean DEFAULT false,
  batch_number integer,
  lab_id text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(class_id, day_index, slot_index, COALESCE(batch_number, 0))
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_timetables_class_day ON public.class_timetables USING btree (class_id, day_index);

COMMENT ON TABLE public.class_timetables IS 'Class schedule/timetable entries';

-- ----------------------------------------------------------------
-- 12.6 SAMPLE DATA FOR NEW TABLES
-- ----------------------------------------------------------------

-- Sample Announcements
INSERT INTO public.announcements (title, content, priority, category, department) VALUES
  ('Mid-Semester Exams', 'Mid-semester examinations will begin from next week. Please check the exam schedule on the notice board.', 'high', 'Academic', 'All'),
  ('Library Hours Extended', 'Library will remain open till 10 PM during exam week for student convenience.', 'normal', 'Facility', 'All'),
  ('Campus Placement Drive', 'Top MNCs will be visiting campus for recruitment. Register before Dec 30.', 'high', 'Career', 'All'),
  ('Winter Break Notice', 'Campus will be closed from Jan 1-5 for winter break. Classes resume on Jan 6.', 'normal', 'General', 'All')
ON CONFLICT DO NOTHING;

-- Sample Events
INSERT INTO public.event ("Ename", "Etype", "Date", "Time", "Location", "Description", capacity, status) VALUES
  ('Tech Symposium 2025', 'Academic', '2025-01-15', '10:00 AM', 'Main Auditorium', 'Annual technology symposium featuring industry experts', 200, 'upcoming'),
  ('Campus Placement Drive', 'Career', '2025-01-20', '09:00 AM', 'Placement Cell', 'Top MNCs recruiting for software engineering roles', 150, 'upcoming'),
  ('Cultural Fest', 'Social', '2025-01-25', '05:00 PM', 'Open Air Theater', 'Annual cultural celebration with music and dance', 500, 'upcoming')
ON CONFLICT DO NOTHING;

-- ================================================================
-- SECTION 13: COMMIT TRANSACTION
-- ================================================================

COMMIT;

-- ================================================================
-- END OF SCHEMA
-- ================================================================

-- Schema Version: 1.0
-- Last Updated: December 31, 2025
-- Total Tables: 16 (11 main + 2 legacy + 3 specialized)
-- Total Views: 2
-- Total Triggers: 5
-- Transaction: Wrapped in BEGIN/COMMIT for atomic execution
-- ================================================================

-- USAGE INSTRUCTIONS:
-- 1. Run this entire file in your PostgreSQL database
-- 2. All tables, views, triggers, and sample data will be created
-- 3. If tables already exist, they will be dropped and recreated
-- 4. The entire operation is wrapped in a transaction for safety
-- ================================================================
